{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-immunedeconv
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.1.0"

source:
  path: .

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, shiny
requirements:
  build:
    - r-devtools >=1.13
    - r-base >=3.4
    - r-dplyr >=0.7
    - r-magrittr >=1.5
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-testit >=0.7
    - r-r.methodss3 >=1.7
    - r-data.tree >=0.7
    - r-e1071 >=1.6
    - bioconductor-biobase >=2.38
    - bioconductor-preprocesscore >=1.40
    - bioconductor-gsva >=1.26
    - bioconductor-sva >=3.26
    - bioconductor-gseabase >=1.40
    - r-xcell
    - r-epic
    - r-mcpcounter
    - r-roxygen2 >=6.0.1
    - posix               # [win]
    - {{native}}toolchain # [win]
      #    - gcc                 # [not win]

  run:
    - r-base >=3.4
    - r-dplyr >=0.7
    - r-magrittr >=1.5
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-testit >=0.7
    - r-r.methodss3 >=1.7
    - r-data.tree >=0.7
    - r-e1071 >=1.6
    - bioconductor-biobase >=2.38
    - bioconductor-preprocesscore >=1.40
    - bioconductor-gsva >=1.26
    - bioconductor-sva >=3.26
    - bioconductor-gseabase >=1.40
    - r-xcell
    - r-epic
    - r-mcpcounter
    - r-roxygen2 >=6.0.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modules')" # [not win]
    - "\"%R%\" -e \"library('modules')\"" # [win]

about:
  home: https://github.com/grst/immune_deconvolution_methods
  license: BSD 3-clause
  summary: collection of methods for immune cell deconvolution from bulk RNA-seq samples.
  license_family: BSD

