blank_issues_enabled: false
contact_links:
  - name: Immunedeconv Community Forum 
    url: https://github.com/icbi-lab/immunedeconv/discussions 
    about: If you have questions about “How to do X”, please ask them here.
