{% set name = "r-immunedeconv" %}

package:
  name: {{ name }}
  version: "develop" 

source:
  path: ".."

build:
  script: $R CMD INSTALL --build .
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-dplyr >=0.7
    - r-magrittr >=1.5
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-testit >=0.7
    - r-tibble >=1.4.2
    - r-data.tree >=0.7
    - r-limsolve >=1.5.5.1
    - r-e1071 >=1.6
    - bioconductor-biobase
    - bioconductor-biocparallel
    - bioconductor-preprocesscore
    - bioconductor-sva
    - r-xcell >=1.2
    - r-epic >=1.1
    - r-mcpcounter
  run:
    - r-base
    - r-dplyr >=0.7
    - r-magrittr >=1.5
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-testit >=0.7
    - r-tibble >=1.4.2
    - r-data.tree >=0.7
    - r-limsolve >=1.5.5.1
    - r-e1071 >=1.6
    - bioconductor-biobase
    - bioconductor-biocparallel
    - bioconductor-preprocesscore
    - bioconductor-sva
    - r-xcell >=1.2
    - r-epic >=1.1
    - r-mcpcounter

test:
  commands:
    - '$R -e "library(''immunedeconv'')"'

about:
  home: https://github.com/icbi-lab/immunedeconv
  license: BSD_3_clause
  summary: "collection of methods for immune cell deconvolution of bulk RNA-seq samples."
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grst
  identifiers:
    - doi:10.1101/463828
